"""empty message

Revision ID: 0a2bd5a7dca1
Revises: c717f1d97915
Create Date: 2021-09-02 06:51:15.819556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2bd5a7dca1'
down_revision = 'c717f1d97915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nameFavorite', sa.String(length=30), nullable=False),
    sa.Column('typeFavorite', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nameFavorite'),
    sa.UniqueConstraint('nameFavorite'),
    sa.UniqueConstraint('typeFavorite'),
    sa.UniqueConstraint('typeFavorite')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
