"""empty message

Revision ID: 2776a7ccedf5
Revises: 
Create Date: 2021-09-02 21:58:59.279606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2776a7ccedf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namePlanets', sa.String(length=30), nullable=False),
    sa.Column('diameterPlanets', sa.String(length=30), nullable=False),
    sa.Column('populationPlanets', sa.String(length=30), nullable=False),
    sa.Column('terrainPlanets', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('hairColor', sa.String(length=30), nullable=False),
    sa.Column('skinColor', sa.String(length=30), nullable=False),
    sa.Column('eyeColor', sa.String(length=30), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('birthYear', sa.String(length=30), nullable=False),
    sa.Column('homeworld', sa.String(length=30), nullable=False),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nameFavorite', sa.String(length=30), nullable=False),
    sa.Column('typeFavorite', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameVehicles', sa.String(length=30), nullable=False),
    sa.Column('modelVehicles', sa.String(length=30), nullable=False),
    sa.Column('manufacturerVehicles', sa.Integer(), nullable=True),
    sa.Column('lengthVehicles', sa.String(length=30), nullable=False),
    sa.Column('classVehicles', sa.String(length=30), nullable=False),
    sa.Column('maxAtmospheringSpeedVehicles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturerVehicles'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('favorite')
    op.drop_table('characters')
    op.drop_table('user')
    op.drop_table('planets')
    # ### end Alembic commands ###
