"""empty message

Revision ID: bbc03d3db0fb
Revises: 0a2bd5a7dca1
Create Date: 2021-09-02 07:15:03.906051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc03d3db0fb'
down_revision = '0a2bd5a7dca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('homeworld', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['homeworld'], ['planets.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('nameFavorite', table_name='favorite')
    op.drop_index('nameFavorite_2', table_name='favorite')
    op.drop_index('typeFavorite', table_name='favorite')
    op.drop_index('typeFavorite_2', table_name='favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('typeFavorite_2', 'favorite', ['typeFavorite'], unique=False)
    op.create_index('typeFavorite', 'favorite', ['typeFavorite'], unique=False)
    op.create_index('nameFavorite_2', 'favorite', ['nameFavorite'], unique=False)
    op.create_index('nameFavorite', 'favorite', ['nameFavorite'], unique=False)
    op.drop_table('characters')
    op.drop_table('planets')
    # ### end Alembic commands ###
